### ISSUE TITLE
一个布尔tensor跟‘-’不匹配的问题

### ISSUE THREAD

**Issue by Ericzh2017** [PengjieRen/GLKS#2]
按照说明预处理并导入数据以后，运行报错，布尔tensor跟‘-’不匹配。
我自己尝试了很久还是没有跑通。
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 320, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `bitwise_not()` operator instead.
请问一下这可能是什么原因导致的呢？

$ python -m torch.distributed.launch --nproc_per_node=1 Run_GLKS.py --mode='train'
1.2.0.dev20190805
10.0.130
7602
item size:  21704
data size:  34486
no_init b_encoder.c_embedding.0.weight torch.Size([21704, 300])
init b_encoder.c_encs.0.weight_ih_l0 torch.Size([384, 300])
init b_encoder.c_encs.0.weight_hh_l0 torch.Size([384, 128])
init b_encoder.c_encs.0.bias_ih_l0 torch.Size([384])
init b_encoder.c_encs.0.bias_hh_l0 torch.Size([384])
init b_encoder.c_encs.0.weight_ih_l0_reverse torch.Size([384, 300])
init b_encoder.c_encs.0.weight_hh_l0_reverse torch.Size([384, 128])
init b_encoder.c_encs.0.bias_ih_l0_reverse torch.Size([384])
init b_encoder.c_encs.0.bias_hh_l0_reverse torch.Size([384])
no_init c_encoder.c_embedding.0.weight torch.Size([21704, 300])
init c_encoder.c_encs.0.weight_ih_l0 torch.Size([384, 300])
init c_encoder.c_encs.0.weight_hh_l0 torch.Size([384, 128])
init c_encoder.c_encs.0.bias_ih_l0 torch.Size([384])
init c_encoder.c_encs.0.bias_hh_l0 torch.Size([384])
init c_encoder.c_encs.0.weight_ih_l0_reverse torch.Size([384, 300])
init c_encoder.c_encs.0.weight_hh_l0_reverse torch.Size([384, 128])
init c_encoder.c_encs.0.bias_ih_l0_reverse torch.Size([384])
init c_encoder.c_encs.0.bias_hh_l0_reverse torch.Size([384])
no_init embedding.weight torch.Size([21704, 300])
init state_tracker.linear.weight torch.Size([256, 512])
init state_tracker.linear.bias torch.Size([256])
init state_tracker.gru.weight_ih_l0 torch.Size([768, 300])
init state_tracker.gru.weight_hh_l0 torch.Size([768, 256])
init state_tracker.gru.bias_ih_l0 torch.Size([768])
init state_tracker.gru.bias_hh_l0 torch.Size([768])
init k_selector.b_highway.nonlinear.0.weight torch.Size([512, 512])
init k_selector.b_highway.nonlinear.0.bias torch.Size([512])
init k_selector.b_highway.nonlinear.1.weight torch.Size([512, 512])
init k_selector.b_highway.nonlinear.1.bias torch.Size([512])
init k_selector.b_highway.linear.0.weight torch.Size([512, 512])
init k_selector.b_highway.linear.0.bias torch.Size([512])
init k_selector.b_highway.linear.1.weight torch.Size([512, 512])
init k_selector.b_highway.linear.1.bias torch.Size([512])
init k_selector.b_highway.gate.0.weight torch.Size([512, 512])
init k_selector.b_highway.gate.0.bias torch.Size([512])
init k_selector.b_highway.gate.1.weight torch.Size([512, 512])
init k_selector.b_highway.gate.1.bias torch.Size([512])
init k_selector.c_highway.nonlinear.0.weight torch.Size([512, 512])
init k_selector.c_highway.nonlinear.0.bias torch.Size([512])
init k_selector.c_highway.nonlinear.1.weight torch.Size([512, 512])
init k_selector.c_highway.nonlinear.1.bias torch.Size([512])
init k_selector.c_highway.linear.0.weight torch.Size([512, 512])
init k_selector.c_highway.linear.0.bias torch.Size([512])
init k_selector.c_highway.linear.1.weight torch.Size([512, 512])
init k_selector.c_highway.linear.1.bias torch.Size([512])
init k_selector.c_highway.gate.0.weight torch.Size([512, 512])
init k_selector.c_highway.gate.0.bias torch.Size([512])
init k_selector.c_highway.gate.1.weight torch.Size([512, 512])
init k_selector.c_highway.gate.1.bias torch.Size([512])
init k_selector.match_attn.linear_key.weight torch.Size([512, 512])
init k_selector.match_attn.linear_query.weight torch.Size([512, 512])
init k_selector.match_attn.linear_query.bias torch.Size([512])
init k_selector.match_attn.v.weight torch.Size([1, 512])
init k_selector.area_attn.linear_key.weight torch.Size([256, 256])
init k_selector.area_attn.linear_query.weight torch.Size([256, 256])
init k_selector.area_attn.linear_query.bias torch.Size([256])
init k_selector.area_attn.v.weight torch.Size([1, 256])
init c_generator.b_attn.linear_key.weight torch.Size([256, 256])
init c_generator.b_attn.linear_query.weight torch.Size([256, 812])
init c_generator.b_attn.linear_query.bias torch.Size([256])
init c_generator.b_attn.v.weight torch.Size([1, 256])
init v_generator.c_attn.linear_key.weight torch.Size([256, 256])
init v_generator.c_attn.linear_query.weight torch.Size([256, 812])
init v_generator.c_attn.linear_query.bias torch.Size([256])
init v_generator.c_attn.v.weight torch.Size([1, 256])
init v_generator.b_attn.linear_key.weight torch.Size([256, 256])
init v_generator.b_attn.linear_query.weight torch.Size([256, 812])
init v_generator.b_attn.linear_query.bias torch.Size([256])
init v_generator.b_attn.v.weight torch.Size([1, 256])
init v_generator.readout.weight torch.Size([256, 1324])
init v_generator.readout.bias torch.Size([256])
init v_generator.generator.weight torch.Size([21704, 256])
init v_generator.generator.bias torch.Size([21704])
init mixture.linear1.weight torch.Size([1, 256])
init mixture.linear1.bias torch.Size([1])
GPU  0
Traceback (most recent call last):
  File "Run_GLKS.py", line 109, in <module>
    train(args)
  File "Run_GLKS.py", line 61, in train
    trainer.train_epoch('ds_mle_mcc_train', train_dataset, collate_fn, batch_size, i, model_optimizer)
  File "/home/cike/KSChat/GLKS/trainers/DefaultTrainer.py", line 88, in train_epoch
    bloss = self.train_batch(epoch, data, method=method, optimizer=optimizer)
  File "/home/cike/KSChat/GLKS/trainers/DefaultTrainer.py", line 43, in train_batch
    loss = self.model(data, method=method)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/distributed.py", line 442, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cike/KSChat/GLKS/GLKS.py", line 259, in forward
    return self.do_train(data, type=method)
  File "/home/cike/KSChat/GLKS/GLKS.py", line 268, in do_train
    encode_output, init_decoder_state, all_decode_output, all_gen_output = decode_to_end(self, data, self.vocab2id, tgt=data['response'])
  File "/home/cike/KSChat/GLKS/Utils.py", line 65, in decode_to_end
    encode_outputs = model.encode(data)
  File "/home/cike/KSChat/GLKS/GLKS.py", line 214, in encode
    segment, p_s, p_g =self.k_selector(b_enc_output, c_enc_output, c_state, data['unstructured_knowledge'].ne(0), data['context'].ne(0))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cike/KSChat/GLKS/GLKS.py", line 80, in forward
    b_score=self.match(b_enc_output, c_enc_output, c_state, b_mask, c_mask)
  File "/home/cike/KSChat/GLKS/GLKS.py", line 55, in match
    matching = matching.masked_fill(1 - c_mask.unsqueeze(1), -float('inf'))
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 320, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `bitwise_not()` operator instead.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-u', 'Run_GLKS.py', '--local_rank=0', '--mode=train']' returned non-zero exit status 1.

**Comment by BonbonKim** [comment]
I encountered the same problem, how did you solve it?
